import { Injectable } from '@nestjs/common';
import { PrismaService } from '../../prisma.service';
import { ExecutionSimulatorService } from './execution-simulator.service';
import * as crypto from 'crypto';

@Injectable()
export class PaperTradingService {
  constructor(
    private prisma: PrismaService,
    private executionSim: ExecutionSimulatorService,
  ) {}

  /**
   * Handle trade signals generated by strategies
   */
  async handleSignal(
    strategyId: string,
    symbol: string,
    signal: 'BUY' | 'SELL' | 'HOLD',
    currentPrice: number,
  ): Promise<void> {
    if (signal === 'HOLD') return;

    const strategy = await this.prisma.strategy.findUnique({ where: { id: strategyId } });
    if (!strategy) return;

    // Generate unique correlation ID for this decision
    const correlationId = `corr_${crypto.randomUUID()}`;

    // Find any open position for this strategy and symbol
    const openTrade = await this.prisma.trade.findFirst({
      where: {
        strategyId,
        symbol,
        status: 'OPEN',
      },
    });

    if (signal === 'BUY') {
      if (openTrade) {
        // Already in a BUY position, skip duplicate entry
        return;
      }

      // Simulate slippage & partial fills on entry
      const fill = await this.executionSim.simulateFill('BUY', currentPrice, 0.1);

      // Open new paper trade
      const trade = await this.prisma.trade.create({
        data: {
          strategyId,
          symbol,
          side: 'BUY',
          type: 'PAPER',
          status: 'OPEN',
          entryPrice: fill.filledPrice,
          quantity: fill.filledQuantity,
          correlationId,
        },
      });

      await this.logAudit(
        strategyId,
        'PAPER_TRADER',
        'EXECUTE_ORDER',
        correlationId,
        {
          action: 'BUY',
          requestedPrice: currentPrice,
          filledPrice: fill.filledPrice,
          quantity: fill.filledQuantity,
          slippage: fill.slippagePct,
          latency: fill.latencyMs,
          tradeId: trade.id,
        },
      );

      console.log(`[PAPER TRADE] BUY order executed for ${symbol} at filled price ${fill.filledPrice.toFixed(2)} (Slippage: ${(fill.slippagePct * 100).toFixed(3)}%)`);
    } else if (signal === 'SELL') {
      if (!openTrade) {
        // No position open, cannot execute exit sell
        return;
      }

      // Simulate slippage on exit
      const fill = await this.executionSim.simulateFill('SELL', currentPrice, openTrade.quantity);

      // Calculate simulated profits (pnl)
      const pnl = (fill.filledPrice - openTrade.entryPrice) * fill.filledQuantity;

      // Close open paper trade
      await this.prisma.trade.update({
        where: { id: openTrade.id },
        data: {
          status: 'CLOSED',
          exitPrice: fill.filledPrice,
          exitTime: new Date(),
          quantity: fill.filledQuantity,
          pnl,
        },
      });

      await this.logAudit(
        strategyId,
        'PAPER_TRADER',
        'EXECUTE_ORDER',
        correlationId,
        {
          action: 'SELL_EXIT',
          requestedPrice: currentPrice,
          filledPrice: fill.filledPrice,
          entryPrice: openTrade.entryPrice,
          quantity: fill.filledQuantity,
          slippage: fill.slippagePct,
          latency: fill.latencyMs,
          pnl,
        },
      );

      console.log(`[PAPER TRADE] SELL exit executed for ${symbol} at filled price ${fill.filledPrice.toFixed(2)}. PnL: $${pnl.toFixed(2)}`);
    }
  }

  /**
   * Helper to write institutional provenance records to database
   */
  private async logAudit(
    strategyId: string,
    module: string,
    action: string,
    correlationId: string,
    data: Record<string, any>,
  ): Promise<void> {
    // Fetch last audit block to chain the hashes
    const lastAudit = await this.prisma.auditDecision.findFirst({
      orderBy: { time: 'desc' },
    });

    const previousHash = lastAudit ? lastAudit.provenance : 'genesis';
    const payload = JSON.stringify({ module, action, correlationId, data });
    
    // Hash calculations (Provenance chain)
    const provenance = crypto
      .createHash('sha256')
      .update(previousHash + payload)
      .digest('hex');

    await this.prisma.auditDecision.create({
      data: {
        strategyId,
        module,
        action,
        correlationId,
        data: JSON.stringify(data),
        provenance,
      },
    });
  }
}
